name: firewatch

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"

  frontend:
    build:
      context: ./frontend/firewatch
    ports:
      - "127.0.0.1:3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend/firewatch
          target: /app
          ignore:
            - node_modules/
            - .next/
            - .git/
            - package.json
            - package-lock.json
            - Dockerfile

        - action: rebuild
          path: ./frontend/firewatch/package.json

        - action: rebuild
          path: ./frontend/firewatch/package-lock.json

        - action: rebuild
          path: ./frontend/firewatch/Dockerfile
